C  CALL SUBROUTINE FST2SAC1 TO GET SAC-SMA MOISTURE STATES 
C
      SUBROUTINE FRZ2SAC1(PX,ZSOIL,SMC,SH2O,NUPL,NSAC,SWLT,RTUZ,RTLZ,
     +           FRZST,SACST,FROST,SACPAR,PRFLAG,CELLID,SMAX)
      
C     PX - PRECIPITATION
C     ZSOIL - SOIL LAYER DEPTHS, M
C     SMC - TOTAL MOISTURE CONTENT OF FROZEN GROUND MODEL LAYERS
C     SH2O - UNFROZEN WATER CONTENT OF FROZEN GROUND MODEL LAYERS
C     NUPL - UPPER SOIL LAYER TO DISTRIBUTE SAC-SMA WATER
C     NSAC - TOTAL NUMBER OF SOIL LAYERS (= NSOIL)
C     SWLT - SOIL WILTING POINT
C     SMAX - SOIL POROSITY -- MAX MOISTURE CONTENT
C     RTUZ, RTLZ - UNITY UNLESS TOTAL SAC LAYER DEPTH != PHYSICAL DEPTH
C     FRZST - ARRAY OF SOIL TEMPERATURES AND LIQUIC WATER STATES
C     SACST - ARRAY OF SAC TOTAL MOISTURE STATES
C     FROST - DEPTH OF FROZEN SOIL 
C     SACPAR - SAC MODEL PARAMETERS

      PARAMETER (FRST_FACT = 5.0)
      REAL ZSOIL(*),SMC(*),SH2O(*),FRZST(*),SACST(*),SACPAR(*)
      REAL LZTWC,LZFSC,LZFPC,LZTWH,LZFSH,LZFPH,LZTWM,LZFPM,LZFSM
      INTEGER PRFLAG,CELLID
      LOGICAL ZONE3

C--      COMMON/FSMCO1/UZTWC,UZFWC,LZTWC,LZFSC,LZFPC,ADIMC,FGCO(6),RSUM(7),
C--     1           PPE,PSC,PTA,PWE,PSH,TSOIL(8)
C--      COMMON/FRZCNST/ FRST_FACT,ZBOT      
           
C  GET UPPER ZONE STATES
      UZTWH=FRZST(6)
      UZFWH=FRZST(7)
      UZTWC=SACST(1)
      UZFWC=SACST(2)
      XH=0.
      XC=0.
      ZONE3 = .FALSE.
      UZTWM = SACPAR(1)
      UZFWM = SACPAR(2)
      XM = 0.
      if (prflag==1)write(*,*)'UPPER ZONE'
      if(prflag==1)write(*,*)'uztwm uzfwm',uztwm,uzfwm
c      WRITE( *, *) 'UZFWH = ', UZFWH, ' UZFWC = ', UZFWC, ' UZTWH = ', 
c     + UZTWH
CBL      CALL FST2SAC1(ZSOIL,SMC,SH2O,2,NUPL,SWLT,RTUZ,UZTWH,UZFWH,XH,
cbl      CALL FST2SAC1(ZSOIL,SMC,SH2O,1,NUPL,SWLT,RTUZ,UZTWH,UZFWH,XH,
      CALL FST2SAC2(ZSOIL,SMC,SH2O,1,NUPL,SWLT,SMAX,RTUZ,UZTWH,UZFWH,XH,
     +     UZTWC,UZFWC,XC,FROST1,PX,ZONE3,UZTWM,UZFWM,XM,PRFLAG,CELLID)

      IF(FROST1 .EQ. 0.) THEN
       FROST=0.
      ELSE
       FROST=-FROST1/FRST_FACT
      ENDIF 
      FRZST(6)=UZTWH
      FRZST(7)=UZFWH
      SACST(1)=UZTWC
      SACST(2)=UZFWC

C  GET LOWER ZONE STATES
      LZTWH=FRZST(8)
      LZFSH=FRZST(9)
      LZFPH=FRZST(10)
      LZTWC=SACST(3)
      LZFSC=SACST(4)
      LZFPC=SACST(5)
      NUP=NUPL+1
      ZONE3 = .TRUE.
      LZTWM=SACPAR(9)
      LZFSM=SACPAR(10)
      LZFPM=SACPAR(11)
c      if (prflag==1) write(*,*)'nup nupl',nup,nupl
      if (prflag==1)write(*,*)'LOWER ZONE'
      if(prflag==1)write(*,*)'lztwm lzfsm lzfpm',lztwm,lzfsm,lzfpm
cbl      CALL FST2SAC1(ZSOIL,SMC,SH2O,NUP,NSAC,SWLT,RTLZ,LZTWH,LZFSH,LZFPH,
      CALL FST2SAC2(ZSOIL,SMC,SH2O,NUP,NSAC,SWLT,SMAX,RTLZ,LZTWH,LZFSH,
     +     LZFPH,LZTWC,LZFSC,LZFPC,FROST2,0.0,ZONE3,LZTWM,LZFSM,LZFPM,
     +     PRFLAG,CELLID)
      
      IF(FROST2 .NE. 0.) FROST=FROST-FROST2/FRST_FACT
      FRZST(8)=LZTWH
      FRZST(9)=LZFSH
      FRZST(10)=LZFPH
      SACST(3)=LZTWC
      SACST(4)=LZFSC
      SACST(5)=LZFPC

      RETURN
      END
            
