C  CALL SUBROUTINE FST2SAC1 TO GET SAC-SMA MOISTURE STATES 
C
      SUBROUTINE SMC2SAC1(ZSOIL,SMC,SH2O,NUPL,NSAC,SWLT,RTUZ,RTLZ,
     +           FRZST,SACST,SACPAR,PRFLAG,CELLID,SMAX)
      
C     ZSOIL - SOIL LAYER DEPTHS, M
C     SMC - TOTAL MOISTURE CONTENT OF FROZEN GROUND MODEL LAYERS
C     SH2O - UNFROZEN WATER CONTENT OF FROZEN GROUND MODEL LAYERS
C     NUPL - UPPER SOIL LAYER TO DISTRIBUTE SAC-SMA WATER
C     NSAC - TOTAL NUMBER OF SOIL LAYERS (= NSOIL)
C     SWLT - SOIL WILTING POINT
C     SMAX - SOIL POROSITY -- MAX MOISTURE CONTENT
C     RTUZ, RTLZ - UNITY UNLESS TOTAL SAC LAYER DEPTH != PHYSICAL DEPTH
C     FRZST - ARRAY OF SOIL TEMPERATURES AND LIQUIC WATER STATES
C     SACST - ARRAY OF SAC TOTAL MOISTURE STATES
C     SACPAR - SAC MODEL PARAMETERS

      REAL ZSOIL(*),SMC(*),SH2O(*),FRZST(*),SACST(*),SACPAR(*)
      REAL LZTWC,LZFSC,LZFPC,LZTWH,LZFSH,LZFPH,LZTWM,LZFPM,LZFSM
      INTEGER PRFLAG,CELLID

C--      COMMON/FSMCO1/UZTWC,UZFWC,LZTWC,LZFSC,LZFPC,ADIMC,FGCO(6),RSUM(7),
C--     1           PPE,PSC,PTA,PWE,PSH,TSOIL(8)
C--      COMMON/FRZCNST/ FRST_FACT,ZBOT      
           
C  GET UPPER ZONE STATES
      UZTWH=FRZST(6)
      UZFWH=FRZST(7)
      UZTWC=SACST(1)
      UZFWC=SACST(2)
      XH=0.
      XC=0.
      UZTWM = SACPAR(1)
      UZFWM = SACPAR(2)
      XM = 0.
      if (prflag==1)write(*,*)'UPPER ZONE SMAX',SMAX
      if(prflag==1)write(*,*)'uztwm uzfwm',uztwm,uzfwm
      CALL H2O2SAC1(ZSOIL,SMC,SH2O,1,NUPL,SWLT,SMAX,RTUZ,UZTWH,UZFWH,XH,
     +     UZTWC,UZFWC,XC,UZTWM,UZFWM,XM,PRFLAG,CELLID)

      FRZST(6)=UZTWH
      FRZST(7)=UZFWH
      SACST(1)=UZTWC
      SACST(2)=UZFWC


C  GET LOWER ZONE STATES
      LZTWH=FRZST(8)
      LZFSH=FRZST(9)
      LZFPH=FRZST(10)
      LZTWC=SACST(3)
      LZFSC=SACST(4)
      LZFPC=SACST(5)
      NUP=NUPL+1
      LZTWM=SACPAR(9)
      LZFSM=SACPAR(10)
      LZFPM=SACPAR(11)
c      if (prflag==1) write(*,*)'nup nupl',nup,nupl
      if (prflag==1)write(*,*)'LOWER ZONE SMAX',SMAX
      if(prflag==1)write(*,*)'lztwm lzfsm lzfpm',lztwm,lzfsm,lzfpm
      CALL H2O2SAC1(ZSOIL,SMC,SH2O,NUP,NSAC,SWLT,SMAX,RTLZ,LZTWH,LZFSH,
     +     LZFPH,LZTWC,LZFSC,LZFPC,LZTWM,LZFSM,LZFPM,PRFLAG,CELLID)
      
      FRZST(8)=LZTWH
      FRZST(9)=LZFSH
      FRZST(10)=LZFPH
      SACST(3)=LZTWC
      SACST(4)=LZFSC
      SACST(5)=LZFPC

      RETURN
      END
            
