SUBROUTINE ALLOCATE_ARRAYS()

  ! UW Land Surface Hydrology Group implementation of Noah model
  ! modified from NLDAS implementation
  ! author: Ted Bohn, tbohn@hydro.washington.edu

  ! ALLOCATES ALMOST ALL GLOBAL DRIVER ARRAYS
  ! (LANDMASK, LAND, Y, and X are all allocated in OPEN_LSC)

  ! Modifications:
  ! 2007-Nov-06 Added T12.							Ben Livneh
  ! 2007-Nov-12 Added LSTSNW.							TJB
  ! 2008-May-05 Added SHDMAX and removed T12, for compatibility with NOAH 2.8.	Ben Livneh
  ! 2008-Jul-15 Added SnowTProf (TPACK).					Ben Livneh
  ! 2008-Jul-15 Added PackWater.						Ben Livneh
  ! 2008-Oct-07 Included SAC parameters for use as unified model         Ben Livneh
  ! 2009-Feb-15 Added Anderson PEMB snow model parameters for unified model Ben Livneh

  ! driverMod contains definitions for all global driver variables
  USE driverMod

  IMPLICIT NONE
      
  ! RCS Id string, for version control
  CHARACTER*60 RCSID
  DATA RCSID/"$Id: ALLOCATE_ARRAYS.f90,v 1.7 2008/07/30 22:33:03 vicadmin Exp $"/

  ! Grid cell geometry
  ALLOCATE(COL(xlen,ylen))
  ALLOCATE(ROW(xlen,ylen))
  ALLOCATE(LAT(xlen,ylen))
  ALLOCATE(LON(xlen,ylen))
  ALLOCATE(CELLID(xlen,ylen))

  ! Land surface characteristics (Noah)
  ALLOCATE(NSOIL(landlen))
  ALLOCATE(SOILDEPTH(landlen,MAXNSOIL))
  ALLOCATE(SOILDEPTH_ACCUM(landlen,MAXNSOIL))
  ALLOCATE(SOILTYP(landlen))
  ALLOCATE(SLOPETYP(landlen))
  ALLOCATE(TBOT(landlen))
  ALLOCATE(VEGTYP(landlen))
  ALLOCATE(SHDFAC(landlen,NMONTHS))
  ALLOCATE(SHDMIN(landlen))
  ALLOCATE(SHDMAX(landlen))
  ALLOCATE(ALBEDO(landlen,NMONTHS))
  ALLOCATE(SNOALB(landlen))
  ALLOCATE(ICE(landlen))
  ALLOCATE(W_WILT(landlen))
  ALLOCATE(W_SAT(landlen))
  ALLOCATE(W_BPOWER(landlen))
  ALLOCATE(W_SAT_HYDC(landlen))
  ALLOCATE(W_SAT_MATP(landlen))
  ALLOCATE(ELEV_2d(landlen))

  ! Land surface characteristics (SAC)
  ALLOCATE(UZTWM_2d(landlen))
  ALLOCATE(UZFWM_2d(landlen))
  ALLOCATE(UZK_2d(landlen))
  ALLOCATE(PCTIM_2d(landlen))
  ALLOCATE(ADIMP_2d(landlen))
  ALLOCATE(RIVA_2d(landlen))
  ALLOCATE(ZPERC_2d(landlen))
  ALLOCATE(REXP_2d(landlen))
  ALLOCATE(LZTWM_2d(landlen))
  ALLOCATE(LZFSM_2d(landlen))
  ALLOCATE(LZFPM_2d(landlen))
  ALLOCATE(LZSK_2d(landlen))
  ALLOCATE(LZPK_2d(landlen))
  ALLOCATE(PFREE_2d(landlen))
  ALLOCATE(SIDE_2d(landlen))
  ALLOCATE(RSERV_2d(landlen))
  ! Sensitivity paramters
  ALLOCATE(WCRIT_2d(landlen))
  ALLOCATE(PSNOW1_2d(landlen))
  ALLOCATE(PSNOW2_2d(landlen))
  ALLOCATE(RICHARDS_2d(landlen))

  ! PE scale/adjustment factors
!  ALLOCATE(PESCALE_2d(landlen))
!  ALLOCATE(PEADJ_2d(NMONTHS,landlen))

  ! Snow elevation band parameters
  ALLOCATE(band_elev(landlen,NBANDS))
  ALLOCATE(band_area(landlen,NBANDS))
  ALLOCATE(band_prec(landlen,NBANDS))
  ALLOCATE(Tfactor(landlen,NBANDS))
  ALLOCATE(Pfactor(landlen,NBANDS))

  ! Grid cell state variables -- added TPACK -Ben Livneh Nov 2007
  ALLOCATE(T1(landlen,NBANDS))
  ALLOCATE(TPACK(landlen,NBANDS))
  ALLOCATE(STC(landlen,NBANDS,MAXNSOIL))
  ALLOCATE(SMC(landlen,NBANDS,MAXNSOIL))
  ALLOCATE(PACH20(landlen,NBANDS))
  ALLOCATE(SH2O(landlen,NBANDS,MAXNSOIL))
  ALLOCATE(CMC(landlen,NBANDS))
  ALLOCATE(SNOWH(landlen,NBANDS))
  ALLOCATE(SNEQV(landlen,NBANDS))
  ALLOCATE(CH(landlen,NBANDS))
  ALLOCATE(CM(landlen,NBANDS))
  ALLOCATE(SNCOVR(landlen,NBANDS))
  ALLOCATE(LSTSNW(landlen,NBANDS))

  ! SAC
  ALLOCATE(UZTWC_2d(landlen,NBANDS))
  ALLOCATE(UZFWC_2d(landlen,NBANDS))
  ALLOCATE(LZTWC_2d(landlen,NBANDS))
  ALLOCATE(LZFSC_2d(landlen,NBANDS))
  ALLOCATE(LZFPC_2d(landlen,NBANDS))
  ALLOCATE(ADIMC_2d(landlen,NBANDS))
  ! SAC-HT
  ALLOCATE(FRZPAR(landlen,13))
  ALLOCATE(FRZST(landlen,NBANDS,10))
  ALLOCATE(SACST(landlen,NBANDS,6))
  ALLOCATE(SACPAR(landlen,16))

  ! PEMB snow model - max 100 layers set by code other E. Anderson
  ALLOCATE(NSNOW(landlen,NBANDS))
  ALLOCATE(DSNOW(landlen,NBANDS,MAXNSNOW))
  ALLOCATE(PSNOW(landlen,NBANDS,MAXNSNOW))
  ALLOCATE(RTTSNOW(landlen,NBANDS,MAXNSNOW))
  ALLOCATE(RTTDTSNOW(landlen,NBANDS,MAXNSNOW))
  ALLOCATE(WTSNOW(landlen,NBANDS,MAXNSNOW))
  ALLOCATE(WTDTSNOW(landlen,NBANDS,MAXNSNOW))
  ALLOCATE(TTSNOW(landlen,NBANDS,MAXNSNOW))
  ALLOCATE(TTDTSNOW(landlen,NBANDS,MAXNSNOW))

  ! Interpolated landcover variables
  ALLOCATE(SHDFAC_D(landlen))
  ALLOCATE(ALBEDO_D(landlen))

  ! Forcing variables
  ALLOCATE(SWdownminus(landlen))
  ALLOCATE(LWdownminus(landlen))
  ALLOCATE(Tairminus(landlen))
  ALLOCATE(Qairminus(landlen))
  ALLOCATE(Rainfminus(landlen))
  ALLOCATE(Snowfminus(landlen))
  ALLOCATE(PSurfminus(landlen))
  ALLOCATE(Windminus(landlen))
  ALLOCATE(SWdownnow(landlen))
  ALLOCATE(LWdownnow(landlen))
  ALLOCATE(Tairnow(landlen))
  ALLOCATE(Qairnow(landlen))
  ALLOCATE(Rainfnow(landlen))
  ALLOCATE(Snowfnow(landlen))
  ALLOCATE(PSurfnow(landlen))
  ALLOCATE(Windnow(landlen))
  ALLOCATE(SWdownplus(landlen))
  ALLOCATE(LWdownplus(landlen))
  ALLOCATE(Tairplus(landlen))
  ALLOCATE(Qairplus(landlen))
  ALLOCATE(Rainfplus(landlen))
  ALLOCATE(Snowfplus(landlen))
  ALLOCATE(PSurfplus(landlen))
  ALLOCATE(Windplus(landlen))
  ALLOCATE(DT_TAIR(landlen))
  ALLOCATE(DT_SPFH(landlen))
  ALLOCATE(DT_PSFC(landlen))
  ALLOCATE(DT_WIND(landlen))
  ALLOCATE(DT_LWDN(landlen))
  ALLOCATE(DT_SOLDN(landlen))
  ALLOCATE(DT_SOLDNB(landlen))
  ALLOCATE(DT_SOLNET(landlen))
  ALLOCATE(DT_PRCP(landlen))
  ALLOCATE(DT_RAIN(landlen))
  ALLOCATE(DT_SNOW(landlen))
  ALLOCATE(Z(landlen))

  ! Intermediate variables
  ALLOCATE(CZMODEL(landlen))
  ALLOCATE(DT_SPFH_SAT(landlen))
  ALLOCATE(DQSDT2(landlen))
  ALLOCATE(TH2(landlen))
  ALLOCATE(SOILM(landlen))
  ALLOCATE(PSISAT(landlen))
  ALLOCATE(LWDN(landlen))
  ALLOCATE(LWDN_MODEL(landlen))
  ALLOCATE(SoilMoistTotal(landlen))
  ALLOCATE(SoilMoistTotal_old(landlen))
  ALLOCATE(SWE_old(landlen))
  ALLOCATE(CanopInt_old(landlen))
  ALLOCATE(SFCSPD(landlen))
  ALLOCATE(PTU(landlen))
  ALLOCATE(ETA(landlen))
  ALLOCATE(H(landlen))
  ALLOCATE(EVAP_total(landlen))
  ALLOCATE(EC1(landlen))
  ALLOCATE(EDIR1(landlen))
  ALLOCATE(ET(landlen,MAXNSOIL))
  ALLOCATE(ETT1(landlen))
  ALLOCATE(ESNOW(landlen))
  ALLOCATE(DRIP(landlen))
  ALLOCATE(DEW(landlen))
  ALLOCATE(BETA(landlen))
  ALLOCATE(ETP(landlen))
  ALLOCATE(S(landlen))
  ALLOCATE(FLX1(landlen))
  ALLOCATE(FLX2(landlen))
  ALLOCATE(FLX3(landlen))
  ALLOCATE(SNOMLT(landlen))
  ALLOCATE(RUNOFF1(landlen))
  ALLOCATE(RUNOFF2(landlen))
  ALLOCATE(RUNOFF3(landlen))
  ALLOCATE(RC(landlen))
  ALLOCATE(PC(landlen))
  ALLOCATE(RSMIN(landlen))
  ALLOCATE(RCS(landlen))
  ALLOCATE(RCT(landlen))
  ALLOCATE(RCQ(landlen))
  ALLOCATE(RCSOIL(landlen))
  ALLOCATE(SOILW(landlen))
  ALLOCATE(SMCDRY(landlen))
  ALLOCATE(SMCREF(landlen))
  ALLOCATE(NROOT(landlen))
  ALLOCATE(RM(landlen))
  ALLOCATE(ACondMax(landlen))
  ALLOCATE(band_area_with_snow(landlen))

  ! Output variables
  ALLOCATE(SWnet(landlen))
  ALLOCATE(LWnet(landlen))
  ALLOCATE(Qle(landlen))
  ALLOCATE(Qh(landlen))
  ALLOCATE(Qg(landlen))
  ALLOCATE(Qf(landlen))
  ALLOCATE(Qv(landlen))
  ALLOCATE(Qa(landlen))
  ALLOCATE(DelSurfHeat(landlen))
  ALLOCATE(DelColdCont(landlen))
  ALLOCATE(Snowf(landlen))
  ALLOCATE(Rainf(landlen))
  ALLOCATE(Evap(landlen))
  ALLOCATE(Qs(landlen))
  ALLOCATE(Qsb(landlen))
  ALLOCATE(Qsm(landlen))
  ALLOCATE(Qfz(landlen))
  ALLOCATE(Qst(landlen))
  ALLOCATE(DelSoilMoist(landlen))
  ALLOCATE(DelSWE(landlen))
  ALLOCATE(DelSurfStor(landlen))
  ALLOCATE(DelIntercept(landlen))
  ALLOCATE(SnowT(landlen))
 !Ben Livneh track effective snowpack temp TPACK = SnowTProf
  ALLOCATE(SnowTProf(landlen))
  ALLOCATE(VegT(landlen))
  ALLOCATE(BaresoilT(landlen))
  ALLOCATE(AvgSurfT(landlen))
  ALLOCATE(RadT(landlen))
  ALLOCATE(Albedo_ALMA(landlen))
  ALLOCATE(SWE(landlen))
  ALLOCATE(UZTWC(landlen))
  ALLOCATE(UZFWC(landlen))
  ALLOCATE(LZTWC(landlen))
  ALLOCATE(LZFPC(landlen))
  ALLOCATE(LZFSC(landlen))
 ! Ben Livneh track pack water and ratio
  ALLOCATE(PackWater(landlen))
  ALLOCATE(SliqFrac(landlen))
  ALLOCATE(SWEVeg(landlen))
  ALLOCATE(SurfStor(landlen))
  ALLOCATE(SoilMoist(landlen,MAXNSOIL))
  ALLOCATE(SoilMoistSac(landlen,6))
  ALLOCATE(SoilTemp(landlen,MAXNSOIL))
  ALLOCATE(SMLiqFrac(landlen,MAXNSOIL))
  ALLOCATE(SMFrozFrac(landlen,MAXNSOIL))
  ALLOCATE(SoilWet(landlen))
  ALLOCATE(PotEvap(landlen))
  ALLOCATE(ECanop(landlen))
  ALLOCATE(TVeg(landlen))
  ALLOCATE(ESoil(landlen))
  ALLOCATE(EWater(landlen))
  ALLOCATE(RootMoist(landlen))
  ALLOCATE(CanopInt(landlen))
  ALLOCATE(EvapSnow(landlen))
  ALLOCATE(SubSnow(landlen))
  ALLOCATE(SubSurf(landlen))
  ALLOCATE(ACond(landlen))
  ALLOCATE(SnowFrac(landlen))
  ALLOCATE(Fdepth(landlen))
  ALLOCATE(Tdepth(landlen))
  ALLOCATE(SAlbedo(landlen))
  ALLOCATE(SatSoil(landlen))
  ALLOCATE(WltSoil(landlen))
  ALLOCATE(SnowDepth(landlen))
  ALLOCATE(PotEvapPE(landlen,NBANDS))

END
